import { MarketResolution, MarketStatus } from "@prisma/client";
import prisma from "../prisma";
import { Market } from "../types/Market";


const markets: Market[] = [
     {
    title: "Will Bitcoin reach $150,000 before the end of 2026?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if Bitcoin reaches or exceeds $150,000 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1fa99.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will India win the 2026 ICC T20 World Cup?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if India wins the 2026 ICC T20 World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3cf.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Manchester City win the Premier League 2026-27?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Manchester City wins the 2026-27 Premier League title.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/26bd.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-06-01T00:00:00.000Z"),
  },
  {
    title: "Will Real Madrid win the UEFA Champions League 2026-27?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Real Madrid wins the 2026-27 UEFA Champions League.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3c6.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-06-15T00:00:00.000Z"),
  },
  {
    title: "Will the US Federal Reserve cut interest rates before the end of 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if the US Federal Reserve announces at least one interest rate cut before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4c9.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Tesla stock close above $300 before the end of 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if Tesla stock closes above $300 on any regular trading day before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4c8.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will EUR/USD trade above 1.15 before the end of 2026?",
    category: "forex",
    type: "YES/NO",
    description: "This market resolves YES if EUR/USD trades above 1.15 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4b1.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a major AI regulation bill pass in the US before 2027?",
    category: "politics",
    type: "YES/NO",
    description: "This market resolves YES if the United States passes a major federal AI regulation bill before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f5f3.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will Carlos Alcaraz win Wimbledon 2026?",
    category: "tennis",
    type: "YES/NO",
    description: "This market resolves YES if Carlos Alcaraz wins the Wimbledon men's singles title in 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3be.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-07-31T23:59:59.000Z"),
  },
  {
    title: "Will a Pacific region team win Valorant Champions 2026?",
    category: "esports",
    type: "YES/NO",
    description: "This market resolves YES if a Pacific region team wins Valorant Champions 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f579.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },{
    title: "Will Ethereum reach $8,000 before the end of 2026?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if Ethereum reaches or exceeds $8,000 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f48e.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Solana reach $500 before the end of 2026?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if Solana reaches or exceeds $500 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/26a1.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Apple announce a major AI device before 2027?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if Apple announces a new major AI-focused hardware product before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4f1.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will Nvidia remain above $1 trillion market cap through 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if Nvidia remains valued above $1 trillion at the end of 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f9e0.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will OpenAI release GPT-6 before the end of 2026?",
    category: "world",
    type: "YES/NO",
    description: "This market resolves YES if OpenAI publicly releases a model named GPT-6 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f916.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will an AI-generated movie win a major film award before 2027?",
    category: "world",
    type: "YES/NO",
    description: "This market resolves YES if a film publicly described as AI-generated or heavily AI-assisted wins a major film award before 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3ac.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will India reach the 2026 T20 World Cup final?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if India reaches the final match of the 2026 ICC T20 World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3cf.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Virat Kohli score an international century in 2026?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if Virat Kohli scores at least one international century in any format during 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3cf.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Argentina win the 2026 FIFA World Cup?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Argentina wins the 2026 FIFA World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f30e.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    title: "Will Brazil win the 2026 FIFA World Cup?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Brazil wins the 2026 FIFA World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/26bd.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    title: "Will Kylian Mbappe be the top scorer of the 2026 FIFA World Cup?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Kylian Mbappe finishes as the top scorer of the 2026 FIFA World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f945.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    title: "Will Novak Djokovic win a Grand Slam title in 2026?",
    category: "tennis",
    type: "YES/NO",
    description: "This market resolves YES if Novak Djokovic wins at least one Grand Slam singles title in 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3be.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Iga Swiatek win the French Open 2026?",
    category: "tennis",
    type: "YES/NO",
    description: "This market resolves YES if Iga Swiatek wins the women's singles title at the French Open 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3be.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-07-31T23:59:59.000Z"),
  },
  {
    title: "Will USD/JPY trade above 170 before the end of 2026?",
    category: "forex",
    type: "YES/NO",
    description: "This market resolves YES if USD/JPY trades above 170 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4b4.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will GBP/USD trade above 1.40 before the end of 2026?",
    category: "forex",
    type: "YES/NO",
    description: "This market resolves YES if GBP/USD trades above 1.40 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4b7.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a new country join NATO before the end of 2026?",
    category: "politics",
    type: "YES/NO",
    description: "This market resolves YES if any new country officially joins NATO before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f1fa-1f1f3.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will the UK hold a general election before the end of 2026?",
    category: "politics",
    type: "YES/NO",
    description: "This market resolves YES if the United Kingdom holds a general election before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f5f3.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will GTA 6 release before the end of 2026?",
    category: "esports",
    type: "YES/NO",
    description: "This market resolves YES if GTA 6 is officially released before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3ae.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will League of Legends Worlds 2026 be won by a Korean team?",
    category: "esports",
    type: "YES/NO",
    description: "This market resolves YES if a Korean team wins League of Legends Worlds 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3ae.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a private company land a spacecraft on Mars before 2027?",
    category: "world",
    type: "YES/NO",
    description: "This market resolves YES if a private company successfully lands a spacecraft on Mars before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f680.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },{
    title: "Will Dogecoin reach $1 before the end of 2026?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if Dogecoin reaches or exceeds $1 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f415.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a spot Solana ETF be approved in the US before 2027?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if a spot Solana ETF is approved in the United States before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4dc.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will the crypto market total cap cross $5 trillion before 2027?",
    category: "crypto",
    type: "YES/NO",
    description: "This market resolves YES if the total cryptocurrency market capitalization crosses $5 trillion before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4b0.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will India win the 2027 Cricket World Cup?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if India wins the 2027 Cricket World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3c6.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Australia win the 2027 Cricket World Cup?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if Australia wins the 2027 Cricket World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3cf.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-12-31T23:59:59.000Z"),
  },
  {
    title: "Will an IPL team score 300+ runs in a match before the end of 2026?",
    category: "cricket",
    type: "YES/NO",
    description: "This market resolves YES if any IPL team scores 300 or more runs in a match before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f525.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will England win the 2026 FIFA World Cup?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if England wins the 2026 FIFA World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    title: "Will France win the 2026 FIFA World Cup?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if France wins the 2026 FIFA World Cup.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f1eb-1f1f7.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-08-01T00:00:00.000Z"),
  },
  {
    title: "Will Barcelona win La Liga 2026-27?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Barcelona wins the 2026-27 La Liga title.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3df.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-06-01T00:00:00.000Z"),
  },
  {
    title: "Will Arsenal win the Premier League 2026-27?",
    category: "football",
    type: "YES/NO",
    description: "This market resolves YES if Arsenal wins the 2026-27 Premier League title.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f6e1.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-06-01T00:00:00.000Z"),
  },
  {
    title: "Will the S&P 500 close above 7,000 before the end of 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if the S&P 500 closes above 7,000 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4ca.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will Microsoft become the world's most valuable company before 2027?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if Microsoft becomes the world's most valuable publicly traded company before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4bb.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will gold reach $4,000 per ounce before the end of 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if gold reaches or exceeds $4,000 per ounce before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f947.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will USD/INR trade above 90 before the end of 2026?",
    category: "forex",
    type: "YES/NO",
    description: "This market resolves YES if USD/INR trades above 90 before December 31, 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4b5.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will gold outperform the S&P 500 in 2026?",
    category: "stocks",
    type: "YES/NO",
    description: "This market resolves YES if gold has a higher percentage return than the S&P 500 during calendar year 2026.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/2696.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2026-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a major country announce a central bank digital currency launch before 2027?",
    category: "world",
    type: "YES/NO",
    description: "This market resolves YES if a major country officially announces the launch of a central bank digital currency before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3e6.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will a new global climate agreement be signed before 2027?",
    category: "world",
    type: "YES/NO",
    description: "This market resolves YES if a new major global climate agreement is signed before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f30d.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
  {
    title: "Will a woman win the US presidential election in 2028?",
    category: "politics",
    type: "YES/NO",
    description: "This market resolves YES if a woman wins the 2028 United States presidential election.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f5fd.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2028-12-31T23:59:59.000Z"),
  },
  {
    title: "Will the next UK Prime Minister be from the Labour Party?",
    category: "politics",
    type: "YES/NO",
    description: "This market resolves YES if the next UK Prime Minister after the current one is from the Labour Party.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f3db.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2028-12-31T23:59:59.000Z"),
  },
  {
    title: "Will a new Counter-Strike Major be won by a North American team before 2027?",
    category: "esports",
    type: "YES/NO",
    description: "This market resolves YES if a North American team wins a Counter-Strike Major before January 1, 2027.",
    image: "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f579.svg",
    status: MarketStatus.ACTIVE,
    resolution: MarketResolution.NULL,
    initialPriceYes: 0.5,
    currentPriceYes: 0.5,
    totalVolume: 0,
    spread: 0,
    yesShares: 0,
    noShares: 0,
    endTime: new Date("2027-01-01T00:00:00.000Z"),
  },
]

async function main(){
    console.log("Welcome to Market Seeder")
    console.log("Seeding markets into database")
    for(const market of markets){
        await prisma.market.upsert({
            where:{
                title:market.title
            },
            update:{},
            create:market
        })
    }

    console.log(`Seeded ${markets.length} markets`)
}

main().catch((error) => {
    console.error("Market seed failed:", error);
    process.exit(1);
}).finally(async () => {
    await prisma.$disconnect()
})